_write_prev_shared() {
    if [[ "${USE_PREV_INSTALL_CONFIG}" == true ]]; then
        print_lc "  Restore 'shared' folder of previous installation"
        rm -rf "${SHARED_PATH}"
        cp -rf "${INSTALLATION_PATH_BACKUP}/${SHARED_FOLDERNAME}" "${SHARED_PATH}"
    fi
}

_write_install_config(){
    echo "
BUILD_LIBZMQ_WITH_DRAFTS_ON_DEVICE=${BUILD_LIBZMQ_WITH_DRAFTS_ON_DEVICE}
ENABLE_STATIC_IP=${ENABLE_STATIC_IP}
CURRENT_GATEWAY=${CURRENT_GATEWAY}
CURRENT_IP_ADDRESS=${CURRENT_IP_ADDRESS}
DISABLE_IPv6=${DISABLE_IPv6}
ENABLE_AUTOHOTSPOT=${ENABLE_AUTOHOTSPOT}
AUTOHOTSPOT_PASSWORD=${AUTOHOTSPOT_PASSWORD}
DISABLE_BLUETOOTH=${DISABLE_BLUETOOTH}
DISABLE_SSH_QOS=${DISABLE_SSH_QOS}
DISABLE_BOOT_SCREEN=${DISABLE_BOOT_SCREEN}
DISABLE_BOOT_LOGS_PRINT=${DISABLE_BOOT_LOGS_PRINT}
SETUP_MPD=${SETUP_MPD}
ENABLE_MPD_OVERWRITE_INSTALL=true
UPDATE_RASPI_OS=${UPDATE_RASPI_OS}
ENABLE_RFID_READER=false
ENABLE_SAMBA=${ENABLE_SAMBA}
ENABLE_WEBAPP=${ENABLE_WEBAPP}
ENABLE_KIOSK_MODE=${ENABLE_KIOSK_MODE}
DISABLE_ONBOARD_AUDIO=${DISABLE_ONBOARD_AUDIO}
DISABLE_ONBOARD_AUDIO_BACKUP=${DISABLE_ONBOARD_AUDIO_BACKUP}
GIT_USE_SSH=${GIT_USE_SSH}
ENABLE_WEBAPP_PROD_DOWNLOAD=${ENABLE_WEBAPP_PROD_DOWNLOAD}
" > "${INSTALL_CONFIG_CURRENT}"
}


_setup_login_message() {
    sudo cp -f "${INSTALLATION_PATH}/resources/system/99-rpi-jukebox-rfid-welcome" "/etc/update-motd.d/99-rpi-jukebox-rfid-welcome"
}

_run_setup_postinstall() {
    _setup_login_message
    _write_prev_shared
    _write_install_config
}

setup_postinstall() {
    run_with_log_frame _run_setup_postinstall "Post install"
}

