name: Test Install Scripts Target

on:
  schedule:
    # run at 5 every sunday
    - cron: '0 5 * * 0'
  push:
    branches-ignore:
      - 'future3/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]

env:
  DOCKER_IMAGE_NAME: rpi-jukebox-rfid-bullseye


jobs:

  prepare:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build Bullseye ARMv7
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        push: false
        file: ./ci/Dockerfile.bullseye.test_install_targets.armv7
        target: base
        platforms: linux/arm/v7
        tags: local/${{ env.DOCKER_IMAGE_NAME }}_base:cache
        cache-from: type=gha,scope=${{ github.ref }}-target
        cache-to: type=gha,mode=max,scope=${{ github.ref }}-target


  test:

    needs: prepare

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test_Script: [run_installation_tests.sh, run_installation_tests2.sh, run_installation_tests3.sh]
        username: [hans] #[pi, hans]
        include:
        #   - username: pi
        #     usergroup: pi
          - username: hans
            usergroup: wurst

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build Bullseye ARMv7
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        push: false
        file: ./ci/Dockerfile.bullseye.test_install_targets.armv7
        target: user
        platforms: linux/arm/v7
        tags: local/${{ env.DOCKER_IMAGE_NAME }}_user:cache
        cache-from: type=gha,scope=${{ github.ref }}-target
        build-args: |
          USER_NAME=${{ matrix.username }}
          USER_GROUP=${{ matrix.usergroup }}
          GIT_BRANCH=${{ github.ref_name }}
          GIT_URL=${{ github.server_url }}/${{ github.repository }}

    - name: Run ${{ matrix.test_Script }} Bullseye ARMv7
      uses: tj-actions/docker-run@v2
      with:
        image: local/${{ env.DOCKER_IMAGE_NAME }}_user:cache
        options: --platform linux/arm/v7
        name: ${{ matrix.test_Script }}
        args: |
          ./${{ matrix.test_Script }}
