name: Test Install Scripts Cache

on:
  schedule:
    # run at 5 every sunday
    - cron: '0 5 * * 0'
  push:
    branches-ignore:
      - 'future3/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]

env:
  DOCKER_IMAGE_NAME: rpi-jukebox-rfid-bullseye
  TEMP_DOCKER_PATH: /tmp/
  CACHE_KEY_SUFFIX: -${{ github.sha }}-${{ github.run_attempt }}


jobs:

  prepare:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build Bullseye ARMv7
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        push: false
        file: ./ci/Dockerfile.bullseye.test_install.armv7
        platforms: linux/arm/v7
        tags: local/${{ env.DOCKER_IMAGE_NAME }}:cache
        cache-from: type=gha,scope=${{ github.ref }}-cache
        cache-to: type=gha,mode=max,scope=${{ github.ref }}-cache
        outputs: type=docker,dest=${{ env.TEMP_DOCKER_PATH }}${{ env.DOCKER_IMAGE_NAME }}.tar
        build-args: |
          USER_NAME=hans
          USER_GROUP=wurst
          GIT_BRANCH=${{ github.ref_name }}
          GIT_URL=${{ github.server_url }}/${{ github.repository }}

    - name: Cache Save Docker Image
      uses: actions/cache/save@v3
      with:
        path: ${{ env.TEMP_DOCKER_PATH }}${{ env.DOCKER_IMAGE_NAME }}.tar
        key: ${{ env.DOCKER_IMAGE_NAME }}${{ env.CACHE_KEY_SUFFIX }}


  test:

    needs: prepare
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test_Script: [run_installation_tests.sh, run_installation_tests2.sh, run_installation_tests3.sh]

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Cache Restore Docker Image
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.TEMP_DOCKER_PATH }}${{ env.DOCKER_IMAGE_NAME }}.tar
        key: ${{ env.DOCKER_IMAGE_NAME }}${{ env.CACHE_KEY_SUFFIX }}
        fail-on-cache-miss: true

    - name: Load Docker Image
      run: |
        docker load --input ${{ env.TEMP_DOCKER_PATH }}${{ env.DOCKER_IMAGE_NAME }}.tar

    - name: Run ${{ matrix.test_Script }} Bullseye ARMv7
      uses: tj-actions/docker-run@v2
      with:
        image: local/${{ env.DOCKER_IMAGE_NAME }}:cache
        options: --platform linux/arm/v7
        name: ${{ matrix.test_Script }}
        args: |
          ./${{ matrix.test_Script }}
