name: Test Build Web App v3

on:
  schedule:
    # run at 18:00 every sunday
    - cron: '0 18 * * 0'
  push:
    branches:
        - 'future3/**'
    paths:
        - '.github/workflows/test_build_webapp_v3.yml'
        - '.github/actions/build-webapp/**'
        - 'src/webapp/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
        - future3/develop
        - future3/main
    paths:
        - '.github/workflows/test_build_webapp_v3.yml'
        - '.github/actions/build-webapp/**'
        - 'src/webapp/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Output vars
        id: vars
        run: |
          echo "webapp_bundle_name=webapp-build.tar.gz" >> $GITHUB_OUTPUT

      - name: Build Web App
        id: build-webapp
        uses: ./.github/actions/build-webapp

      - name: Create Bundle
        working-directory: ${{ steps.build-webapp.outputs.webapp-root-path }}
        run: |
          tar -czvf ${{ steps.vars.outputs.webapp_bundle_name }} build

      - name: Artifact Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.vars.outputs.webapp_bundle_name }}
          path: ${{ steps.build-webapp.outputs.webapp-root-path }}/${{ steps.vars.outputs.webapp_bundle_name }}
          retention-days: 5
